//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HES.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HES.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to turn off the alarm and unlock all workstations?.
        /// </summary>
        internal static string Alarm_DisableAlarm_Body {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your password to confirm.
        /// </summary>
        internal static string Alarm_DisableAlarm_Confirm {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn off alarm.
        /// </summary>
        internal static string Alarm_DisableAlarm_Title {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All workstations are unlocked..
        /// </summary>
        internal static string Alarm_DisableAlarm_Toast {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to turn on the alarm and lock all workstations?.
        /// </summary>
        internal static string Alarm_EnableAlarm_Body {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn on alarm.
        /// </summary>
        internal static string Alarm_EnableAlarm_Title {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All workstations are locked..
        /// </summary>
        internal static string Alarm_EnableAlarm_Toast {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This button allows you to remotely lock workstations and block the connection of hardware vaults..
        /// </summary>
        internal static string Alarm_PageDescription {
            get {
                return ResourceManager.GetString("Alarm_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alarm Button.
        /// </summary>
        internal static string Alarm_PageHeader {
            get {
                return ResourceManager.GetString("Alarm_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        internal static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string Btn_Filters {
            get {
                return ResourceManager.GetString("Btn_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        internal static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn Off.
        /// </summary>
        internal static string Btn_TurnOff {
            get {
                return ResourceManager.GetString("Btn_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn On.
        /// </summary>
        internal static string Btn_TurnOn {
            get {
                return ResourceManager.GetString("Btn_TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Tasks.
        /// </summary>
        internal static string Dashboard_HardwareVaultTasks_Title {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Label_AccountType {
            get {
                return ResourceManager.GetString("Label_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        internal static string Label_Active {
            get {
                return ResourceManager.GetString("Label_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrators.
        /// </summary>
        internal static string Label_Administrators {
            get {
                return ResourceManager.GetString("Label_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audit.
        /// </summary>
        internal static string Label_Audit {
            get {
                return ResourceManager.GetString("Label_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Sessions Count Per Day.
        /// </summary>
        internal static string Label_AvgSessionsCountPerDay {
            get {
                return ResourceManager.GetString("Label_AvgSessionsCountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Sessions Duration.
        /// </summary>
        internal static string Label_AvgSessionsDuration {
            get {
                return ResourceManager.GetString("Label_AvgSessionsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Total Duartion By Employee.
        /// </summary>
        internal static string Label_AvgTotalDuartionByEmployee {
            get {
                return ResourceManager.GetString("Label_AvgTotalDuartionByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Total Sessions Count By Employee.
        /// </summary>
        internal static string Label_AvgTotalSessionsCountByEmployee {
            get {
                return ResourceManager.GetString("Label_AvgTotalSessionsCountByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Working Hours Per Day.
        /// </summary>
        internal static string Label_AvgWorkingHoursPerDay {
            get {
                return ResourceManager.GetString("Label_AvgWorkingHoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Days And Employees.
        /// </summary>
        internal static string Label_ByDaysAndEmployees {
            get {
                return ResourceManager.GetString("Label_ByDaysAndEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Departments.
        /// </summary>
        internal static string Label_ByDepartments {
            get {
                return ResourceManager.GetString("Label_ByDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Employees.
        /// </summary>
        internal static string Label_ByEmployees {
            get {
                return ResourceManager.GetString("Label_ByEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Workstations.
        /// </summary>
        internal static string Label_ByWorkstations {
            get {
                return ResourceManager.GetString("Label_ByWorkstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company.
        /// </summary>
        internal static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        internal static string Label_Created {
            get {
                return ResourceManager.GetString("Label_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard.
        /// </summary>
        internal static string Label_Dashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Protection.
        /// </summary>
        internal static string Label_DataProtection {
            get {
                return ResourceManager.GetString("Label_DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        internal static string Label_Department {
            get {
                return ResourceManager.GetString("Label_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled by.
        /// </summary>
        internal static string Label_DisabledBy {
            get {
                return ResourceManager.GetString("Label_DisabledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        internal static string Label_Employee {
            get {
                return ResourceManager.GetString("Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        internal static string Label_Employees {
            get {
                return ResourceManager.GetString("Label_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees Count.
        /// </summary>
        internal static string Label_EmployeesCount {
            get {
                return ResourceManager.GetString("Label_EmployeesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled by.
        /// </summary>
        internal static string Label_EnabledBy {
            get {
                return ResourceManager.GetString("Label_EnabledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Date.
        /// </summary>
        internal static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event.
        /// </summary>
        internal static string Label_Event {
            get {
                return ResourceManager.GetString("Label_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        internal static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groups.
        /// </summary>
        internal static string Label_Groups {
            get {
                return ResourceManager.GetString("Label_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault.
        /// </summary>
        internal static string Label_HardwareVault {
            get {
                return ResourceManager.GetString("Label_HardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults.
        /// </summary>
        internal static string Label_HardwareVaults {
            get {
                return ResourceManager.GetString("Label_HardwareVaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Orders.
        /// </summary>
        internal static string Label_LicenseOrders {
            get {
                return ResourceManager.GetString("Label_LicenseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Never used.
        /// </summary>
        internal static string Label_NeverUsed {
            get {
                return ResourceManager.GetString("Label_NeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        internal static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation.
        /// </summary>
        internal static string Label_Operation {
            get {
                return ResourceManager.GetString("Label_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrgStructure.
        /// </summary>
        internal static string Label_OrgStructure {
            get {
                return ResourceManager.GetString("Label_OrgStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        internal static string Label_Parameters {
            get {
                return ResourceManager.GetString("Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session.
        /// </summary>
        internal static string Label_Session {
            get {
                return ResourceManager.GetString("Label_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sessions.
        /// </summary>
        internal static string Label_Sessions {
            get {
                return ResourceManager.GetString("Label_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sessions Count.
        /// </summary>
        internal static string Label_SessionsCount {
            get {
                return ResourceManager.GetString("Label_SessionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Severity.
        /// </summary>
        internal static string Label_Severity {
            get {
                return ResourceManager.GetString("Label_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Accounts.
        /// </summary>
        internal static string Label_SharedAccounts {
            get {
                return ResourceManager.GetString("Label_SharedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Vaults.
        /// </summary>
        internal static string Label_SoftwareVaults {
            get {
                return ResourceManager.GetString("Label_SoftwareVaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Date.
        /// </summary>
        internal static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summaries.
        /// </summary>
        internal static string Label_Summaries {
            get {
                return ResourceManager.GetString("Label_Summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        internal static string Label_Templates {
            get {
                return ResourceManager.GetString("Label_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sessions Count.
        /// </summary>
        internal static string Label_TotalSessionsCount {
            get {
                return ResourceManager.GetString("Label_TotalSessionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sessions Duration.
        /// </summary>
        internal static string Label_TotalSessionsDuration {
            get {
                return ResourceManager.GetString("Label_TotalSessionsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked By.
        /// </summary>
        internal static string Label_UnlockedBy {
            get {
                return ResourceManager.GetString("Label_UnlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault Access Profiles.
        /// </summary>
        internal static string Label_VaultAccessProfiles {
            get {
                return ResourceManager.GetString("Label_VaultAccessProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working Days Count.
        /// </summary>
        internal static string Label_WorkingDaysCount {
            get {
                return ResourceManager.GetString("Label_WorkingDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation.
        /// </summary>
        internal static string Label_Workstation {
            get {
                return ResourceManager.GetString("Label_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations.
        /// </summary>
        internal static string Label_Workstations {
            get {
                return ResourceManager.GetString("Label_Workstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations Count.
        /// </summary>
        internal static string Label_WorkstationsCount {
            get {
                return ResourceManager.GetString("Label_WorkstationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations Online.
        /// </summary>
        internal static string Label_WorkstationsOnline {
            get {
                return ResourceManager.GetString("Label_WorkstationsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summary.
        /// </summary>
        internal static string Summary_PageTitle {
            get {
                return ResourceManager.GetString("Summary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string Title_Filter {
            get {
                return ResourceManager.GetString("Title_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock all workstations.
        /// </summary>
        internal static string Title_LockAll {
            get {
                return ResourceManager.GetString("Title_LockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long Pending.
        /// </summary>
        internal static string Title_LongPending {
            get {
                return ResourceManager.GetString("Title_LongPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh table.
        /// </summary>
        internal static string Title_RefreshTable {
            get {
                return ResourceManager.GetString("Title_RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock all workstations.
        /// </summary>
        internal static string Title_UnlockAll {
            get {
                return ResourceManager.GetString("Title_UnlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Events.
        /// </summary>
        internal static string WorkstationEvents_PageTitle {
            get {
                return ResourceManager.GetString("WorkstationEvents_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Sessions.
        /// </summary>
        internal static string WorkstationSessions_PageTitle {
            get {
                return ResourceManager.GetString("WorkstationSessions_PageTitle", resourceCulture);
            }
        }
    }
}
