//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HES.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HES.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to turn off the alarm and unlock all workstations?.
        /// </summary>
        internal static string Alarm_DisableAlarm_Body {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your password to confirm.
        /// </summary>
        internal static string Alarm_DisableAlarm_Confirm {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn off alarm.
        /// </summary>
        internal static string Alarm_DisableAlarm_Title {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All workstations are unlocked..
        /// </summary>
        internal static string Alarm_DisableAlarm_Toast {
            get {
                return ResourceManager.GetString("Alarm_DisableAlarm_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to turn on the alarm and lock all workstations?.
        /// </summary>
        internal static string Alarm_EnableAlarm_Body {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn on alarm.
        /// </summary>
        internal static string Alarm_EnableAlarm_Title {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All workstations are locked..
        /// </summary>
        internal static string Alarm_EnableAlarm_Toast {
            get {
                return ResourceManager.GetString("Alarm_EnableAlarm_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This button allows you to remotely lock workstations and block the connection of hardware vaults..
        /// </summary>
        internal static string Alarm_PageDescription {
            get {
                return ResourceManager.GetString("Alarm_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alarm Button.
        /// </summary>
        internal static string Alarm_PageHeader {
            get {
                return ResourceManager.GetString("Alarm_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Hardware Vault.
        /// </summary>
        internal static string Btn_AddHardwareVault {
            get {
                return ResourceManager.GetString("Btn_AddHardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Shared Account.
        /// </summary>
        internal static string Btn_AddSharedAccount {
            get {
                return ResourceManager.GetString("Btn_AddSharedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        internal static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string Btn_Copy {
            get {
                return ResourceManager.GetString("Btn_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create employee.
        /// </summary>
        internal static string Btn_CreateEmployee {
            get {
                return ResourceManager.GetString("Btn_CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Personal Account.
        /// </summary>
        internal static string Btn_CreatePersonalAccount {
            get {
                return ResourceManager.GetString("Btn_CreatePersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string Btn_Details {
            get {
                return ResourceManager.GetString("Btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable.
        /// </summary>
        internal static string Btn_Disable {
            get {
                return ResourceManager.GetString("Btn_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable SSO.
        /// </summary>
        internal static string Btn_DisableSSO {
            get {
                return ResourceManager.GetString("Btn_DisableSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        internal static string Btn_Done {
            get {
                return ResourceManager.GetString("Btn_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit OTP.
        /// </summary>
        internal static string Btn_EditOTP {
            get {
                return ResourceManager.GetString("Btn_EditOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Password.
        /// </summary>
        internal static string Btn_EditPassword {
            get {
                return ResourceManager.GetString("Btn_EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable.
        /// </summary>
        internal static string Btn_Enable {
            get {
                return ResourceManager.GetString("Btn_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable SSO.
        /// </summary>
        internal static string Btn_EnableSSO {
            get {
                return ResourceManager.GetString("Btn_EnableSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string Btn_Filter {
            get {
                return ResourceManager.GetString("Btn_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string Btn_Filters {
            get {
                return ResourceManager.GetString("Btn_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate.
        /// </summary>
        internal static string Btn_Generate {
            get {
                return ResourceManager.GetString("Btn_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        internal static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend.
        /// </summary>
        internal static string Btn_Resend {
            get {
                return ResourceManager.GetString("Btn_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send email.
        /// </summary>
        internal static string Btn_SendEmail {
            get {
                return ResourceManager.GetString("Btn_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as primary.
        /// </summary>
        internal static string Btn_SetAsPrimary {
            get {
                return ResourceManager.GetString("Btn_SetAsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        internal static string Btn_Show {
            get {
                return ResourceManager.GetString("Btn_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip.
        /// </summary>
        internal static string Btn_Skip {
            get {
                return ResourceManager.GetString("Btn_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync Now.
        /// </summary>
        internal static string Btn_SyncNow {
            get {
                return ResourceManager.GetString("Btn_SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync with AD.
        /// </summary>
        internal static string Btn_SyncWithAD {
            get {
                return ResourceManager.GetString("Btn_SyncWithAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn Off.
        /// </summary>
        internal static string Btn_TurnOff {
            get {
                return ResourceManager.GetString("Btn_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn On.
        /// </summary>
        internal static string Btn_TurnOn {
            get {
                return ResourceManager.GetString("Btn_TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Tasks.
        /// </summary>
        internal static string Dashboard_HardwareVaultTasks_Title {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultTasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add hardware vault.
        /// </summary>
        internal static string EmployeeDetails_AddHardwareVault_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_AddHardwareVault_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault added..
        /// </summary>
        internal static string EmployeeDetails_AddHardwareVault_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_AddHardwareVault_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no accounts, you can create a shared account on the Shared Account page..
        /// </summary>
        internal static string EmployeeDetails_AddSharedAccount_NoAccounts {
            get {
                return ResourceManager.GetString("EmployeeDetails_AddSharedAccount_NoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add shared account.
        /// </summary>
        internal static string EmployeeDetails_AddSharedAccount_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_AddSharedAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account added and will be recorded when the device is connected to the server..
        /// </summary>
        internal static string EmployeeDetails_AddSharedAccount_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_AddSharedAccount_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete account.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_DeleteAccount {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete invitation.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_DeleteInvitation {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_DeleteInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit personal account.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_EditPersonalAccount {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_EditPersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit personal account OTP.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_EditPersonalAccountOtp {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_EditPersonalAccountOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit personal account password.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_EditPersonalAccountPwd {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_EditPersonalAccountPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Details.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_HardwareVaultDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_HardwareVaultDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove hardware vault from employee.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_RemoveHardwareVault {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_RemoveHardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend invitation.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_ResendInvitation {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_ResendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as primary account.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_SetAsPrimary {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_SetAsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show activation code.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_ShowActivationCode {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_ShowActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Vault Details.
        /// </summary>
        internal static string EmployeeDetails_BtnTitle_SoftwareVaultDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails_BtnTitle_SoftwareVaultDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter data manually or select from the template:.
        /// </summary>
        internal static string EmployeeDetails_CreatePersonalAccount_EnterData {
            get {
                return ResourceManager.GetString("EmployeeDetails_CreatePersonalAccount_EnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create personal account.
        /// </summary>
        internal static string EmployeeDetails_CreatePersonalAccount_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_CreatePersonalAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account created..
        /// </summary>
        internal static string EmployeeDetails_CreatePersonalAccount_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_CreatePersonalAccount_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You want to delete {0} account {1}?.
        /// </summary>
        internal static string EmployeeDetails_DeleteAccount_Body {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteAccount_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Account.
        /// </summary>
        internal static string EmployeeDetails_DeleteAccount_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account deleted..
        /// </summary>
        internal static string EmployeeDetails_DeleteAccount_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteAccount_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You want to remove vault {0}? When removing the last vault, all accounts will be deleted..
        /// </summary>
        internal static string EmployeeDetails_DeleteHardwareVault_Body {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteHardwareVault_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Hardware Vault.
        /// </summary>
        internal static string EmployeeDetails_DeleteHardwareVault_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteHardwareVault_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault removed..
        /// </summary>
        internal static string EmployeeDetails_DeleteHardwareVault_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_DeleteHardwareVault_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to disable SSO for {0}?.
        /// </summary>
        internal static string EmployeeDetails_DisableSso_Body {
            get {
                return ResourceManager.GetString("EmployeeDetails_DisableSso_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable SSO.
        /// </summary>
        internal static string EmployeeDetails_DisableSso_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_DisableSso_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO disabled..
        /// </summary>
        internal static string EmployeeDetails_DisableSso_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_DisableSso_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit personal account.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccount_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account updated..
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccount_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccount_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit personal account OTP.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountOtp_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountOtp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account OTP updated..
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountOtp_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountOtp_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current cryptographic strength.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_CryptographicStrength {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_CryptographicStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Lower Case.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_IsLowerCase {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_IsLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Numeric.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_IsNumeric {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_IsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Spec Char.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_IsSpecChar {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_IsSpecChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Upper Case.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_IsUpperCase {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_IsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length {0}.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_Length {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit account password.
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account password updated..
        /// </summary>
        internal static string EmployeeDetails_EditPersonalAccountPwd_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_EditPersonalAccountPwd_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to enable SSO for {0}?.
        /// </summary>
        internal static string EmployeeDetails_EnableSso_Body {
            get {
                return ResourceManager.GetString("EmployeeDetails_EnableSso_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable SSO.
        /// </summary>
        internal static string EmployeeDetails_EnableSso_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_EnableSso_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO enabled..
        /// </summary>
        internal static string EmployeeDetails_EnableSso_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_EnableSso_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware vault details.
        /// </summary>
        internal static string EmployeeDetails_HardwareVaultDetails_Title {
            get {
                return ResourceManager.GetString("EmployeeDetails_HardwareVaultDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License status None.
        /// </summary>
        internal static string EmployeeDetails_Label_LicenseNone {
            get {
                return ResourceManager.GetString("EmployeeDetails_Label_LicenseNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License till {0}.
        /// </summary>
        internal static string EmployeeDetails_Label_LicenseTill {
            get {
                return ResourceManager.GetString("EmployeeDetails_Label_LicenseTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Primary account.
        /// </summary>
        internal static string EmployeeDetails_Label_PrimaryAccount {
            get {
                return ResourceManager.GetString("EmployeeDetails_Label_PrimaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set this account as a primary account?.
        /// </summary>
        internal static string EmployeeDetails_SetAsWorkstationAccount_Body {
            get {
                return ResourceManager.GetString("EmployeeDetails_SetAsWorkstationAccount_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account setted as primary..
        /// </summary>
        internal static string EmployeeDetails_SetAsWorkstationAccount_Toast {
            get {
                return ResourceManager.GetString("EmployeeDetails_SetAsWorkstationAccount_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Vault invite sent.
        /// </summary>
        internal static string EmployeeDetails_SoftwareVaultInviteSent {
            get {
                return ResourceManager.GetString("EmployeeDetails_SoftwareVaultInviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1} already exists..
        /// </summary>
        internal static string Employees_CreateEmployee_EmployeeAlreadyExists {
            get {
                return ResourceManager.GetString("Employees_CreateEmployee_EmployeeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, select a vault..
        /// </summary>
        internal static string Employees_CreateEmployee_SelectVault {
            get {
                return ResourceManager.GetString("Employees_CreateEmployee_SelectVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can send the code to the email.
        /// </summary>
        internal static string Employees_CreateEmployee_SendEmail {
            get {
                return ResourceManager.GetString("Employees_CreateEmployee_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Employee.
        /// </summary>
        internal static string Employees_CreateEmployee_Title {
            get {
                return ResourceManager.GetString("Employees_CreateEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee created..
        /// </summary>
        internal static string Employees_CreateEmployee_Toast {
            get {
                return ResourceManager.GetString("Employees_CreateEmployee_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You want to delete employee {0}? Also all events and sessions will be deleted..
        /// </summary>
        internal static string Employees_DeleteEmployee_Body {
            get {
                return ResourceManager.GetString("Employees_DeleteEmployee_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Employee.
        /// </summary>
        internal static string Employees_DeleteEmployee_Title {
            get {
                return ResourceManager.GetString("Employees_DeleteEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee removed..
        /// </summary>
        internal static string Employees_DeleteEmployee_Toast {
            get {
                return ResourceManager.GetString("Employees_DeleteEmployee_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The employee {0} is tied device, first untie the device to remove the employee..
        /// </summary>
        internal static string Employees_DeleteEmployee_UntieDevice {
            get {
                return ResourceManager.GetString("Employees_DeleteEmployee_UntieDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Employee.
        /// </summary>
        internal static string Employees_EditEmployee_Title {
            get {
                return ResourceManager.GetString("Employees_EditEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee updated..
        /// </summary>
        internal static string Employees_EditEmployee_Toast {
            get {
                return ResourceManager.GetString("Employees_EditEmployee_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To sync users from the active directory, set domain settings on the parameters page..
        /// </summary>
        internal static string Employees_SyncEmployeesWithAD_Alert {
            get {
                return ResourceManager.GetString("Employees_SyncEmployeesWithAD_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync with Active Directory.
        /// </summary>
        internal static string Employees_SyncEmployeesWithAD_Title {
            get {
                return ResourceManager.GetString("Employees_SyncEmployeesWithAD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Name.
        /// </summary>
        internal static string Label_AccountName {
            get {
                return ResourceManager.GetString("Label_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        internal static string Label_Accounts {
            get {
                return ResourceManager.GetString("Label_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Label_AccountType {
            get {
                return ResourceManager.GetString("Label_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activation.
        /// </summary>
        internal static string Label_Activation {
            get {
                return ResourceManager.GetString("Label_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activation code.
        /// </summary>
        internal static string Label_ActivationCode {
            get {
                return ResourceManager.GetString("Label_ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        internal static string Label_Active {
            get {
                return ResourceManager.GetString("Label_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AD.
        /// </summary>
        internal static string Label_AD {
            get {
                return ResourceManager.GetString("Label_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrators.
        /// </summary>
        internal static string Label_Administrators {
            get {
                return ResourceManager.GetString("Label_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apps.
        /// </summary>
        internal static string Label_Apps {
            get {
                return ResourceManager.GetString("Label_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audit.
        /// </summary>
        internal static string Label_Audit {
            get {
                return ResourceManager.GetString("Label_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Sessions Count Per Day.
        /// </summary>
        internal static string Label_AvgSessionsCountPerDay {
            get {
                return ResourceManager.GetString("Label_AvgSessionsCountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Sessions Duration.
        /// </summary>
        internal static string Label_AvgSessionsDuration {
            get {
                return ResourceManager.GetString("Label_AvgSessionsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Total Duartion By Employee.
        /// </summary>
        internal static string Label_AvgTotalDuartionByEmployee {
            get {
                return ResourceManager.GetString("Label_AvgTotalDuartionByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Total Sessions Count By Employee.
        /// </summary>
        internal static string Label_AvgTotalSessionsCountByEmployee {
            get {
                return ResourceManager.GetString("Label_AvgTotalSessionsCountByEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avg Working Hours Per Day.
        /// </summary>
        internal static string Label_AvgWorkingHoursPerDay {
            get {
                return ResourceManager.GetString("Label_AvgWorkingHoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battery.
        /// </summary>
        internal static string Label_Battery {
            get {
                return ResourceManager.GetString("Label_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Days And Employees.
        /// </summary>
        internal static string Label_ByDaysAndEmployees {
            get {
                return ResourceManager.GetString("Label_ByDaysAndEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Departments.
        /// </summary>
        internal static string Label_ByDepartments {
            get {
                return ResourceManager.GetString("Label_ByDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Employees.
        /// </summary>
        internal static string Label_ByEmployees {
            get {
                return ResourceManager.GetString("Label_ByEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Workstations.
        /// </summary>
        internal static string Label_ByWorkstations {
            get {
                return ResourceManager.GetString("Label_ByWorkstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company.
        /// </summary>
        internal static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        internal static string Label_Created {
            get {
                return ResourceManager.GetString("Label_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard.
        /// </summary>
        internal static string Label_Dashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Protection.
        /// </summary>
        internal static string Label_DataProtection {
            get {
                return ResourceManager.GetString("Label_DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на day.
        /// </summary>
        internal static string Label_Day {
            get {
                return ResourceManager.GetString("Label_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days.
        /// </summary>
        internal static string Label_Days {
            get {
                return ResourceManager.GetString("Label_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        internal static string Label_Department {
            get {
                return ResourceManager.GetString("Label_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled by.
        /// </summary>
        internal static string Label_DisabledBy {
            get {
                return ResourceManager.GetString("Label_DisabledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain.
        /// </summary>
        internal static string Label_Domain {
            get {
                return ResourceManager.GetString("Label_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        internal static string Label_Employee {
            get {
                return ResourceManager.GetString("Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        internal static string Label_Employees {
            get {
                return ResourceManager.GetString("Label_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees Count.
        /// </summary>
        internal static string Label_EmployeesCount {
            get {
                return ResourceManager.GetString("Label_EmployeesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled by.
        /// </summary>
        internal static string Label_EnabledBy {
            get {
                return ResourceManager.GetString("Label_EnabledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Date.
        /// </summary>
        internal static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Pwd.
        /// </summary>
        internal static string Label_EnterPwd {
            get {
                return ResourceManager.GetString("Label_EnterPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event.
        /// </summary>
        internal static string Label_Event {
            get {
                return ResourceManager.GetString("Label_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        internal static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Name.
        /// </summary>
        internal static string Label_FullName {
            get {
                return ResourceManager.GetString("Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate Pwd.
        /// </summary>
        internal static string Label_GeneratePwd {
            get {
                return ResourceManager.GetString("Label_GeneratePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groups.
        /// </summary>
        internal static string Label_Groups {
            get {
                return ResourceManager.GetString("Label_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault.
        /// </summary>
        internal static string Label_HardwareVault {
            get {
                return ResourceManager.GetString("Label_HardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults.
        /// </summary>
        internal static string Label_HardwareVaults {
            get {
                return ResourceManager.GetString("Label_HardwareVaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imported At.
        /// </summary>
        internal static string Label_ImportedAt {
            get {
                return ResourceManager.GetString("Label_ImportedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Seen.
        /// </summary>
        internal static string Label_LastSeen {
            get {
                return ResourceManager.GetString("Label_LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Synced.
        /// </summary>
        internal static string Label_LastSynced {
            get {
                return ResourceManager.GetString("Label_LastSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License End Date.
        /// </summary>
        internal static string Label_LicenseEndDate {
            get {
                return ResourceManager.GetString("Label_LicenseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Orders.
        /// </summary>
        internal static string Label_LicenseOrders {
            get {
                return ResourceManager.GetString("Label_LicenseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Status.
        /// </summary>
        internal static string Label_LicenseStatus {
            get {
                return ResourceManager.GetString("Label_LicenseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login Type.
        /// </summary>
        internal static string Label_LoginType {
            get {
                return ResourceManager.GetString("Label_LoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAC.
        /// </summary>
        internal static string Label_MAC {
            get {
                return ResourceManager.GetString("Label_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Need Sync.
        /// </summary>
        internal static string Label_NeedSync {
            get {
                return ResourceManager.GetString("Label_NeedSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Never used.
        /// </summary>
        internal static string Label_NeverUsed {
            get {
                return ResourceManager.GetString("Label_NeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        internal static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online.
        /// </summary>
        internal static string Label_Online {
            get {
                return ResourceManager.GetString("Label_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation.
        /// </summary>
        internal static string Label_Operation {
            get {
                return ResourceManager.GetString("Label_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrgStructure.
        /// </summary>
        internal static string Label_OrgStructure {
            get {
                return ResourceManager.GetString("Label_OrgStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OTP Updated.
        /// </summary>
        internal static string Label_OtpUpdated {
            get {
                return ResourceManager.GetString("Label_OtpUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overview.
        /// </summary>
        internal static string Label_Overview {
            get {
                return ResourceManager.GetString("Label_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        internal static string Label_Parameters {
            get {
                return ResourceManager.GetString("Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal account.
        /// </summary>
        internal static string Label_PersonalAccount {
            get {
                return ResourceManager.GetString("Label_PersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        internal static string Label_PhoneNumber {
            get {
                return ResourceManager.GetString("Label_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        internal static string Label_Position {
            get {
                return ResourceManager.GetString("Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        internal static string Label_Profile {
            get {
                return ResourceManager.GetString("Label_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password Updated.
        /// </summary>
        internal static string Label_PwdUpdated {
            get {
                return ResourceManager.GetString("Label_PwdUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        internal static string Label_Reason {
            get {
                return ResourceManager.GetString("Label_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string Label_Remove {
            get {
                return ResourceManager.GetString("Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID.
        /// </summary>
        internal static string Label_RFID {
            get {
                return ResourceManager.GetString("Label_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security Key.
        /// </summary>
        internal static string Label_SecurityKey {
            get {
                return ResourceManager.GetString("Label_SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the reason.
        /// </summary>
        internal static string Label_SelectReason {
            get {
                return ResourceManager.GetString("Label_SelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Serial Number.
        /// </summary>
        internal static string Label_SerialNumber {
            get {
                return ResourceManager.GetString("Label_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session.
        /// </summary>
        internal static string Label_Session {
            get {
                return ResourceManager.GetString("Label_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sessions.
        /// </summary>
        internal static string Label_Sessions {
            get {
                return ResourceManager.GetString("Label_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sessions Count.
        /// </summary>
        internal static string Label_SessionsCount {
            get {
                return ResourceManager.GetString("Label_SessionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Severity.
        /// </summary>
        internal static string Label_Severity {
            get {
                return ResourceManager.GetString("Label_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared account.
        /// </summary>
        internal static string Label_SharedAccount {
            get {
                return ResourceManager.GetString("Label_SharedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Accounts.
        /// </summary>
        internal static string Label_SharedAccounts {
            get {
                return ResourceManager.GetString("Label_SharedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Sign On.
        /// </summary>
        internal static string Label_SingleSignOn {
            get {
                return ResourceManager.GetString("Label_SingleSignOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Vaults.
        /// </summary>
        internal static string Label_SoftwareVaults {
            get {
                return ResourceManager.GetString("Label_SoftwareVaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO Disabled.
        /// </summary>
        internal static string Label_SSODisabled {
            get {
                return ResourceManager.GetString("Label_SSODisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO Enabled.
        /// </summary>
        internal static string Label_SSOEnabled {
            get {
                return ResourceManager.GetString("Label_SSOEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Date.
        /// </summary>
        internal static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summaries.
        /// </summary>
        internal static string Label_Summaries {
            get {
                return ResourceManager.GetString("Label_Summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        internal static string Label_Templates {
            get {
                return ResourceManager.GetString("Label_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sessions Count.
        /// </summary>
        internal static string Label_TotalSessionsCount {
            get {
                return ResourceManager.GetString("Label_TotalSessionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Sessions Duration.
        /// </summary>
        internal static string Label_TotalSessionsDuration {
            get {
                return ResourceManager.GetString("Label_TotalSessionsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked By.
        /// </summary>
        internal static string Label_UnlockedBy {
            get {
                return ResourceManager.GetString("Label_UnlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated.
        /// </summary>
        internal static string Label_Updated {
            get {
                return ResourceManager.GetString("Label_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URLs.
        /// </summary>
        internal static string Label_Urls {
            get {
                return ResourceManager.GetString("Label_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Logon Name.
        /// </summary>
        internal static string Label_UserLogonName {
            get {
                return ResourceManager.GetString("Label_UserLogonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        internal static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault Access Profiles.
        /// </summary>
        internal static string Label_VaultAccessProfiles {
            get {
                return ResourceManager.GetString("Label_VaultAccessProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaults.
        /// </summary>
        internal static string Label_Vaults {
            get {
                return ResourceManager.GetString("Label_Vaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaults Count.
        /// </summary>
        internal static string Label_VaultsCount {
            get {
                return ResourceManager.GetString("Label_VaultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working Days Count.
        /// </summary>
        internal static string Label_WorkingDaysCount {
            get {
                return ResourceManager.GetString("Label_WorkingDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation.
        /// </summary>
        internal static string Label_Workstation {
            get {
                return ResourceManager.GetString("Label_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations.
        /// </summary>
        internal static string Label_Workstations {
            get {
                return ResourceManager.GetString("Label_Workstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations Count.
        /// </summary>
        internal static string Label_WorkstationsCount {
            get {
                return ResourceManager.GetString("Label_WorkstationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations Online.
        /// </summary>
        internal static string Label_WorkstationsOnline {
            get {
                return ResourceManager.GetString("Label_WorkstationsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, select a hardware vault..
        /// </summary>
        internal static string Message_SelectHardwareVault {
            get {
                return ResourceManager.GetString("Message_SelectHardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summary.
        /// </summary>
        internal static string Summary_PageTitle {
            get {
                return ResourceManager.GetString("Summary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot add more than one hardware vault..
        /// </summary>
        internal static string Title_CannotAddMoreHardwareVault {
            get {
                return ResourceManager.GetString("Title_CannotAddMoreHardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete employee.
        /// </summary>
        internal static string Title_DeleteEmployee {
            get {
                return ResourceManager.GetString("Title_DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit employee.
        /// </summary>
        internal static string Title_EditEmployee {
            get {
                return ResourceManager.GetString("Title_EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee details.
        /// </summary>
        internal static string Title_EmployeeDetails {
            get {
                return ResourceManager.GetString("Title_EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string Title_Filter {
            get {
                return ResourceManager.GetString("Title_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imported from Active Directory.
        /// </summary>
        internal static string Title_ImportedFromActiveDirectory {
            get {
                return ResourceManager.GetString("Title_ImportedFromActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock all workstations.
        /// </summary>
        internal static string Title_LockAll {
            get {
                return ResourceManager.GetString("Title_LockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long Pending.
        /// </summary>
        internal static string Title_LongPending {
            get {
                return ResourceManager.GetString("Title_LongPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh table.
        /// </summary>
        internal static string Title_RefreshTable {
            get {
                return ResourceManager.GetString("Title_RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock all workstations.
        /// </summary>
        internal static string Title_UnlockAll {
            get {
                return ResourceManager.GetString("Title_UnlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Events.
        /// </summary>
        internal static string WorkstationEvents_PageTitle {
            get {
                return ResourceManager.GetString("WorkstationEvents_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Sessions.
        /// </summary>
        internal static string WorkstationSessions_PageTitle {
            get {
                return ResourceManager.GetString("WorkstationSessions_PageTitle", resourceCulture);
            }
        }
    }
}
