// <auto-generated />
using System;
using HES.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HES.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210514070828_added_culture_field")]
    partial class added_culture_field
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("HES.Core.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Apps")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtpSecret")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PasswordUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SharedAccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("StorageId")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<uint>("Timestamp")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("UpdateInActiveDirectory")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Urls")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SharedAccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HES.Core.Entities.AppSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Culture")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("HES.Core.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HES.Core.Entities.DataProtection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtection");
                });

            modelBuilder.Entity("HES.Core.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HES.Core.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActiveDirectoryGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrimaryAccountId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("WhenChanged")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HES.Core.Entities.FidoStoredCredential", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("CredType")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorJson")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityKeyName")
                        .HasColumnType("longtext");

                    b.Property<uint>("SignatureCounter")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("UserHandle")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("longblob");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FidoStoredCredential");
                });

            modelBuilder.Entity("HES.Core.Entities.Group", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("ChangePasswordWhenExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HES.Core.Entities.GroupMembership", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVault", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Battery")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Firmware")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HardwareVaultProfileId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasNewLicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsStatusApplied")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LicenseEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LicenseStatus")
                        .HasColumnType("int");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MasterPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedSync")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RFID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("StatusReason")
                        .HasColumnType("int");

                    b.Property<uint>("Timestamp")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HardwareVaultProfileId");

                    b.HasIndex("MAC")
                        .IsUnique();

                    b.HasIndex("RFID")
                        .IsUnique();

                    b.ToTable("HardwareVaults");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultActivation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AcivationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VaultId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HardwareVaultActivations");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultLicense", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HardwareVaultId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LicenseOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareVaultId");

                    b.HasIndex("LicenseOrderId");

                    b.ToTable("HardwareVaultLicenses");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultProfile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("ButtonConnection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ButtonPairing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ButtonStorageAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MasterKeyConnection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MasterKeyPairing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MasterKeyStorageAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PinConnection")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PinExpiration")
                        .HasColumnType("int");

                    b.Property<int>("PinLength")
                        .HasColumnType("int");

                    b.Property<bool>("PinPairing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PinStorageAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PinTryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("HardwareVaultProfiles");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HardwareVaultId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OtpSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<uint>("Timestamp")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HardwareVaultId");

                    b.ToTable("HardwareVaultTasks");
                });

            modelBuilder.Entity("HES.Core.Entities.LicenseOrder", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<bool>("ProlongExistingLicenses")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LicenseOrders");
                });

            modelBuilder.Entity("HES.Core.Entities.Position", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("HES.Core.Entities.SharedAccount", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apps")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtpSecret")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpSecretChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Urls")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SharedAccounts");
                });

            modelBuilder.Entity("HES.Core.Entities.SoftwareVault", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientAppVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasNewLicense")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LicenseEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LicenseStatus")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedSync")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SoftwareVaults");
                });

            modelBuilder.Entity("HES.Core.Entities.SoftwareVaultInvitation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ActivationCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoftwareVaultId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SoftwareVaultId");

                    b.ToTable("SoftwareVaultInvitations");
                });

            modelBuilder.Entity("HES.Core.Entities.Template", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apps")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Urls")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("HES.Core.Entities.Workstation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<bool>("RFID")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationEvent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("HardwareVaultId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("UserSession")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkstationId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HardwareVaultId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkstationEvents");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationHardwareVaultPair", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HardwareVaultId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LockProximity")
                        .HasColumnType("int");

                    b.Property<int>("LockTimeout")
                        .HasColumnType("int");

                    b.Property<int>("UnlockProximity")
                        .HasColumnType("int");

                    b.Property<string>("WorkstationId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareVaultId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkstationHardwareVaultPairs");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HardwareVaultId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnlockedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserSession")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkstationId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HardwareVaultId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkstationSessions");
                });

            modelBuilder.Entity("HES.Core.Models.Audit.SummaryByDayAndEmployee", b =>
                {
                    b.Property<TimeSpan>("AvgSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Employee")
                        .HasColumnType("longtext");

                    b.Property<int>("SessionsCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<int>("WorkstationsCount")
                        .HasColumnType("int");

                    b.ToTable("SummaryByDayAndEmployee");
                });

            modelBuilder.Entity("HES.Core.Models.Audit.SummaryByDepartments", b =>
                {
                    b.Property<TimeSpan>("AvgSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("AvgTotalDuartionByEmployee")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("AvgTotalSessionsCountByEmployee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeesCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessionsCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<int>("WorkstationsCount")
                        .HasColumnType("int");

                    b.ToTable("SummaryByDepartments");
                });

            modelBuilder.Entity("HES.Core.Models.Audit.SummaryByEmployees", b =>
                {
                    b.Property<decimal>("AvgSessionsCountPerDay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<TimeSpan>("AvgSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("AvgWorkingHoursPerDay")
                        .HasColumnType("time(6)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Employee")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalSessionsCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<int>("WorkingDaysCount")
                        .HasColumnType("int");

                    b.Property<int>("WorkstationsCount")
                        .HasColumnType("int");

                    b.ToTable("SummaryByEmployees");
                });

            modelBuilder.Entity("HES.Core.Models.Audit.SummaryByWorkstations", b =>
                {
                    b.Property<TimeSpan>("AvgSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("AvgTotalDuartionByEmployee")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("AvgTotalSessionsCountByEmployee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EmployeesCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessionsCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalSessionsDuration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Workstation")
                        .HasColumnType("longtext");

                    b.ToTable("SummaryByWorkstations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HES.Core.Entities.Account", b =>
                {
                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("Accounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HES.Core.Entities.SharedAccount", "SharedAccount")
                        .WithMany()
                        .HasForeignKey("SharedAccountId");

                    b.Navigation("Employee");

                    b.Navigation("SharedAccount");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("HES.Core.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HES.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HES.Core.Entities.Department", b =>
                {
                    b.HasOne("HES.Core.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HES.Core.Entities.Employee", b =>
                {
                    b.HasOne("HES.Core.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HES.Core.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HES.Core.Entities.GroupMembership", b =>
                {
                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HES.Core.Entities.Group", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVault", b =>
                {
                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("HardwareVaults")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("HES.Core.Entities.HardwareVaultProfile", "HardwareVaultProfile")
                        .WithMany("HardwareVaults")
                        .HasForeignKey("HardwareVaultProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("HardwareVaultProfile");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultLicense", b =>
                {
                    b.HasOne("HES.Core.Entities.HardwareVault", "HardwareVault")
                        .WithMany()
                        .HasForeignKey("HardwareVaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HES.Core.Entities.LicenseOrder", "LicenseOrder")
                        .WithMany("HardwareVaultLicenses")
                        .HasForeignKey("LicenseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareVault");

                    b.Navigation("LicenseOrder");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultTask", b =>
                {
                    b.HasOne("HES.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("HES.Core.Entities.HardwareVault", "HardwareVault")
                        .WithMany("HardwareVaultTasks")
                        .HasForeignKey("HardwareVaultId");

                    b.Navigation("Account");

                    b.Navigation("HardwareVault");
                });

            modelBuilder.Entity("HES.Core.Entities.SoftwareVault", b =>
                {
                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("SoftwareVaults")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HES.Core.Entities.SoftwareVaultInvitation", b =>
                {
                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("SoftwareVaultInvitations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HES.Core.Entities.SoftwareVault", "SoftwareVault")
                        .WithMany()
                        .HasForeignKey("SoftwareVaultId");

                    b.Navigation("Employee");

                    b.Navigation("SoftwareVault");
                });

            modelBuilder.Entity("HES.Core.Entities.Workstation", b =>
                {
                    b.HasOne("HES.Core.Entities.Department", "Department")
                        .WithMany("Workstations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationEvent", b =>
                {
                    b.HasOne("HES.Core.Entities.Account", "Account")
                        .WithMany("WorkstationEvents")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HES.Core.Entities.Department", "Department")
                        .WithMany("WorkstationEvents")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("WorkstationEvents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HES.Core.Entities.HardwareVault", "HardwareVault")
                        .WithMany()
                        .HasForeignKey("HardwareVaultId");

                    b.HasOne("HES.Core.Entities.Workstation", "Workstation")
                        .WithMany("WorkstationEvents")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("HardwareVault");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationHardwareVaultPair", b =>
                {
                    b.HasOne("HES.Core.Entities.HardwareVault", "HardwareVault")
                        .WithMany()
                        .HasForeignKey("HardwareVaultId");

                    b.HasOne("HES.Core.Entities.Workstation", "Workstation")
                        .WithMany("WorkstationProximityVaults")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HardwareVault");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("HES.Core.Entities.WorkstationSession", b =>
                {
                    b.HasOne("HES.Core.Entities.Account", "Account")
                        .WithMany("WorkstationSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HES.Core.Entities.Department", "Department")
                        .WithMany("WorkstationSessions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HES.Core.Entities.Employee", "Employee")
                        .WithMany("WorkstationSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HES.Core.Entities.HardwareVault", "HardwareVault")
                        .WithMany()
                        .HasForeignKey("HardwareVaultId");

                    b.HasOne("HES.Core.Entities.Workstation", "Workstation")
                        .WithMany("WorkstationSessions")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("HardwareVault");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HES.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HES.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HES.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HES.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HES.Core.Entities.Account", b =>
                {
                    b.Navigation("WorkstationEvents");

                    b.Navigation("WorkstationSessions");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HES.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HES.Core.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("HES.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("WorkstationEvents");

                    b.Navigation("Workstations");

                    b.Navigation("WorkstationSessions");
                });

            modelBuilder.Entity("HES.Core.Entities.Employee", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("GroupMemberships");

                    b.Navigation("HardwareVaults");

                    b.Navigation("SoftwareVaultInvitations");

                    b.Navigation("SoftwareVaults");

                    b.Navigation("WorkstationEvents");

                    b.Navigation("WorkstationSessions");
                });

            modelBuilder.Entity("HES.Core.Entities.Group", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVault", b =>
                {
                    b.Navigation("HardwareVaultTasks");
                });

            modelBuilder.Entity("HES.Core.Entities.HardwareVaultProfile", b =>
                {
                    b.Navigation("HardwareVaults");
                });

            modelBuilder.Entity("HES.Core.Entities.LicenseOrder", b =>
                {
                    b.Navigation("HardwareVaultLicenses");
                });

            modelBuilder.Entity("HES.Core.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HES.Core.Entities.Workstation", b =>
                {
                    b.Navigation("WorkstationEvents");

                    b.Navigation("WorkstationProximityVaults");

                    b.Navigation("WorkstationSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
