//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HES.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HES.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_EmployeesCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long open session (&gt;12h).
        /// </summary>
        public static string Dashboard_EmployeesCard_LongOpenSession {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_LongOpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-hideez unlock (24h).
        /// </summary>
        public static string Dashboard_EmployeesCard_NonHideezUnlock {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_NonHideezUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened Sessions.
        /// </summary>
        public static string Dashboard_EmployeesCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        public static string Dashboard_EmployeesCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License critical.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseCritical {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License expired.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseExpired {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License warning.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseWarning {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low battery.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LowBattery {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault locked.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_VaultLocked {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_VaultLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/HideezGroup/HES.
        /// </summary>
        public static string Dashboard_ServerCard_LeftLink {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_LeftLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HES version.
        /// </summary>
        public static string Dashboard_ServerCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long pending tasks.
        /// </summary>
        public static string Dashboard_ServerCard_LongPendingTasks {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_LongPendingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Tasks.
        /// </summary>
        public static string Dashboard_ServerCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hideez Enterprise Server.
        /// </summary>
        public static string Dashboard_ServerCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_WorkstationsCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online.
        /// </summary>
        public static string Dashboard_WorkstationsCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations.
        /// </summary>
        public static string Dashboard_WorkstationsCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for approval.
        /// </summary>
        public static string Dashboard_WorkstationsCard_WaitingForApproval {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_WaitingForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        public static string Display_Account {
            get {
                return ResourceManager.GetString("Display_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Type.
        /// </summary>
        public static string Display_AccountType {
            get {
                return ResourceManager.GetString("Display_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company.
        /// </summary>
        public static string Display_Company {
            get {
                return ResourceManager.GetString("Display_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        public static string Display_Department {
            get {
                return ResourceManager.GetString("Display_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        public static string Display_Employee {
            get {
                return ResourceManager.GetString("Display_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Date.
        /// </summary>
        public static string Display_EndDate {
            get {
                return ResourceManager.GetString("Display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event.
        /// </summary>
        public static string Display_Event {
            get {
                return ResourceManager.GetString("Display_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault.
        /// </summary>
        public static string Display_HardwareVault {
            get {
                return ResourceManager.GetString("Display_HardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Display_Note {
            get {
                return ResourceManager.GetString("Display_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Severity.
        /// </summary>
        public static string Display_Severity {
            get {
                return ResourceManager.GetString("Display_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Date.
        /// </summary>
        public static string Display_StartDate {
            get {
                return ResourceManager.GetString("Display_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked By.
        /// </summary>
        public static string Display_UnlockedBy {
            get {
                return ResourceManager.GetString("Display_UnlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Session.
        /// </summary>
        public static string Display_UserSession {
            get {
                return ResourceManager.GetString("Display_UserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation.
        /// </summary>
        public static string Display_Workstation {
            get {
                return ResourceManager.GetString("Display_Workstation", resourceCulture);
            }
        }
    }
}
