//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HES.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HES.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrators.
        /// </summary>
        public static string Breadcrumbs_Administrators {
            get {
                return ResourceManager.GetString("Breadcrumbs_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alarm.
        /// </summary>
        public static string Breadcrumbs_Alarm {
            get {
                return ResourceManager.GetString("Breadcrumbs_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audit.
        /// </summary>
        public static string Breadcrumbs_Audit {
            get {
                return ResourceManager.GetString("Breadcrumbs_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard.
        /// </summary>
        public static string Breadcrumbs_Dashboard {
            get {
                return ResourceManager.GetString("Breadcrumbs_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Protection.
        /// </summary>
        public static string Breadcrumbs_DataProtection {
            get {
                return ResourceManager.GetString("Breadcrumbs_DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        public static string Breadcrumbs_Employees {
            get {
                return ResourceManager.GetString("Breadcrumbs_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groups.
        /// </summary>
        public static string Breadcrumbs_Groups {
            get {
                return ResourceManager.GetString("Breadcrumbs_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Access Profiles.
        /// </summary>
        public static string Breadcrumbs_HardwareVaultAccessProfiles {
            get {
                return ResourceManager.GetString("Breadcrumbs_HardwareVaultAccessProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults.
        /// </summary>
        public static string Breadcrumbs_HardwareVaults {
            get {
                return ResourceManager.GetString("Breadcrumbs_HardwareVaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Orders.
        /// </summary>
        public static string Breadcrumbs_LicenseOrders {
            get {
                return ResourceManager.GetString("Breadcrumbs_LicenseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Organization Structure.
        /// </summary>
        public static string Breadcrumbs_OrgStructure {
            get {
                return ResourceManager.GetString("Breadcrumbs_OrgStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        public static string Breadcrumbs_Parameters {
            get {
                return ResourceManager.GetString("Breadcrumbs_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Breadcrumbs_Profile {
            get {
                return ResourceManager.GetString("Breadcrumbs_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Breadcrumbs_Settings {
            get {
                return ResourceManager.GetString("Breadcrumbs_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Accounts.
        /// </summary>
        public static string Breadcrumbs_SharedAccounts {
            get {
                return ResourceManager.GetString("Breadcrumbs_SharedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summaries.
        /// </summary>
        public static string Breadcrumbs_Summaries {
            get {
                return ResourceManager.GetString("Breadcrumbs_Summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        public static string Breadcrumbs_Templates {
            get {
                return ResourceManager.GetString("Breadcrumbs_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Events.
        /// </summary>
        public static string Breadcrumbs_WorkstationEvents {
            get {
                return ResourceManager.GetString("Breadcrumbs_WorkstationEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations.
        /// </summary>
        public static string Breadcrumbs_Workstations {
            get {
                return ResourceManager.GetString("Breadcrumbs_Workstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation Sessions.
        /// </summary>
        public static string Breadcrumbs_WorkstationSessions {
            get {
                return ResourceManager.GetString("Breadcrumbs_WorkstationSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_EmployeesCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long open session (&gt;12h).
        /// </summary>
        public static string Dashboard_EmployeesCard_LongOpenSession {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_LongOpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-hideez unlock (24h).
        /// </summary>
        public static string Dashboard_EmployeesCard_NonHideezUnlock {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_NonHideezUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened Sessions.
        /// </summary>
        public static string Dashboard_EmployeesCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employees.
        /// </summary>
        public static string Dashboard_EmployeesCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_EmployeesCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License critical.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseCritical {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License expired.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseExpired {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License warning.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LicenseWarning {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LicenseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low battery.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_LowBattery {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault locked.
        /// </summary>
        public static string Dashboard_HardwareVaultsCard_VaultLocked {
            get {
                return ResourceManager.GetString("Dashboard_HardwareVaultsCard_VaultLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server Version.
        /// </summary>
        public static string Dashboard_ServerCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long pending tasks.
        /// </summary>
        public static string Dashboard_ServerCard_LongPendingTasks {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_LongPendingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault Tasks.
        /// </summary>
        public static string Dashboard_ServerCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server.
        /// </summary>
        public static string Dashboard_ServerCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_ServerCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registered.
        /// </summary>
        public static string Dashboard_WorkstationsCard_LeftText {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online.
        /// </summary>
        public static string Dashboard_WorkstationsCard_RightText {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstations.
        /// </summary>
        public static string Dashboard_WorkstationsCard_Title {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for approval.
        /// </summary>
        public static string Dashboard_WorkstationsCard_WaitingForApproval {
            get {
                return ResourceManager.GetString("Dashboard_WorkstationsCard_WaitingForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API Address.
        /// </summary>
        public static string Dispaly_ApiAddress {
            get {
                return ResourceManager.GetString("Dispaly_ApiAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API Key.
        /// </summary>
        public static string Dispaly_ApiKey {
            get {
                return ResourceManager.GetString("Dispaly_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Password Change.
        /// </summary>
        public static string Dispaly_AutoPasswordChange {
            get {
                return ResourceManager.GetString("Dispaly_AutoPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain Name.
        /// </summary>
        public static string Dispaly_DomainName {
            get {
                return ResourceManager.GetString("Dispaly_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host.
        /// </summary>
        public static string Dispaly_Host {
            get {
                return ResourceManager.GetString("Dispaly_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Token.
        /// </summary>
        public static string Dispaly_Token {
            get {
                return ResourceManager.GetString("Dispaly_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Logon Name.
        /// </summary>
        public static string Dispaly_UserLogonName {
            get {
                return ResourceManager.GetString("Dispaly_UserLogonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        public static string Display_Account {
            get {
                return ResourceManager.GetString("Display_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Name.
        /// </summary>
        public static string Display_AccountName {
            get {
                return ResourceManager.GetString("Display_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Type.
        /// </summary>
        public static string Display_AccountType {
            get {
                return ResourceManager.GetString("Display_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added.
        /// </summary>
        public static string Display_Added {
            get {
                return ResourceManager.GetString("Display_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approved.
        /// </summary>
        public static string Display_Approved {
            get {
                return ResourceManager.GetString("Display_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applications.
        /// </summary>
        public static string Display_Apps {
            get {
                return ResourceManager.GetString("Display_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applications (separate by semicolon).
        /// </summary>
        public static string Display_AppsSeparate {
            get {
                return ResourceManager.GetString("Display_AppsSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assertion Consumer Service.
        /// </summary>
        public static string Display_AssertionConsumerService {
            get {
                return ResourceManager.GetString("Display_AssertionConsumerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticator code.
        /// </summary>
        public static string Display_AuthenticatorCode {
            get {
                return ResourceManager.GetString("Display_AuthenticatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battery.
        /// </summary>
        public static string Display_Battery {
            get {
                return ResourceManager.GetString("Display_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client Version.
        /// </summary>
        public static string Display_ClientVersion {
            get {
                return ResourceManager.GetString("Display_ClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company.
        /// </summary>
        public static string Display_Company {
            get {
                return ResourceManager.GetString("Display_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm New Password.
        /// </summary>
        public static string Display_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Display_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password.
        /// </summary>
        public static string Display_ConfirmPassword {
            get {
                return ResourceManager.GetString("Display_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact Email.
        /// </summary>
        public static string Display_ContactEmail {
            get {
                return ResourceManager.GetString("Display_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string Display_Created {
            get {
                return ResourceManager.GetString("Display_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created At From.
        /// </summary>
        public static string Display_CreatedAtDateFrom {
            get {
                return ResourceManager.GetString("Display_CreatedAtDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created At To.
        /// </summary>
        public static string Display_CreatedAtDateTo {
            get {
                return ResourceManager.GetString("Display_CreatedAtDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Email.
        /// </summary>
        public static string Display_CurrentEmail {
            get {
                return ResourceManager.GetString("Display_CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Password.
        /// </summary>
        public static string Display_CurrentPassword {
            get {
                return ResourceManager.GetString("Display_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        public static string Display_Department {
            get {
                return ResourceManager.GetString("Display_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain.
        /// </summary>
        public static string Display_Domain {
            get {
                return ResourceManager.GetString("Display_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Display_Email {
            get {
                return ResourceManager.GetString("Display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        public static string Display_Employee {
            get {
                return ResourceManager.GetString("Display_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Date.
        /// </summary>
        public static string Display_EndDate {
            get {
                return ResourceManager.GetString("Display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event.
        /// </summary>
        public static string Display_Event {
            get {
                return ResourceManager.GetString("Display_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External ID.
        /// </summary>
        public static string Display_External_Id {
            get {
                return ResourceManager.GetString("Display_External_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware.
        /// </summary>
        public static string Display_Firmware {
            get {
                return ResourceManager.GetString("Display_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Name.
        /// </summary>
        public static string Display_FirstName {
            get {
                return ResourceManager.GetString("Display_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault.
        /// </summary>
        public static string Display_HardwareVault {
            get {
                return ResourceManager.GetString("Display_HardwareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vaults Count.
        /// </summary>
        public static string Display_HardwareVaultsCount {
            get {
                return ResourceManager.GetString("Display_HardwareVaultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Display_Id {
            get {
                return ResourceManager.GetString("Display_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP.
        /// </summary>
        public static string Display_IP {
            get {
                return ResourceManager.GetString("Display_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Issuer.
        /// </summary>
        public static string Display_Issuer {
            get {
                return ResourceManager.GetString("Display_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Name.
        /// </summary>
        public static string Display_LastName {
            get {
                return ResourceManager.GetString("Display_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Seen.
        /// </summary>
        public static string Display_LastSeen {
            get {
                return ResourceManager.GetString("Display_LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Seen End Date.
        /// </summary>
        public static string Display_LastSeenEndDate {
            get {
                return ResourceManager.GetString("Display_LastSeenEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Seen Start Date.
        /// </summary>
        public static string Display_LastSeenStartDate {
            get {
                return ResourceManager.GetString("Display_LastSeenStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Synced.
        /// </summary>
        public static string Display_LastSynced {
            get {
                return ResourceManager.GetString("Display_LastSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License End Date.
        /// </summary>
        public static string Display_LicenseEndDate {
            get {
                return ResourceManager.GetString("Display_LicenseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License End Date From.
        /// </summary>
        public static string Display_LicenseEndDateFrom {
            get {
                return ResourceManager.GetString("Display_LicenseEndDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License End Date To.
        /// </summary>
        public static string Display_LicenseEndDateTo {
            get {
                return ResourceManager.GetString("Display_LicenseEndDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Start Date From.
        /// </summary>
        public static string Display_LicenseStartDateFrom {
            get {
                return ResourceManager.GetString("Display_LicenseStartDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Start Date To.
        /// </summary>
        public static string Display_LicenseStartDateTo {
            get {
                return ResourceManager.GetString("Display_LicenseStartDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Status.
        /// </summary>
        public static string Display_LicenseStatus {
            get {
                return ResourceManager.GetString("Display_LicenseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Display_Login {
            get {
                return ResourceManager.GetString("Display_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login Type.
        /// </summary>
        public static string Display_LoginType {
            get {
                return ResourceManager.GetString("Display_LoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAC.
        /// </summary>
        public static string Display_MAC {
            get {
                return ResourceManager.GetString("Display_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model.
        /// </summary>
        public static string Display_Model {
            get {
                return ResourceManager.GetString("Display_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Display_Name {
            get {
                return ResourceManager.GetString("Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name Identifier Field.
        /// </summary>
        public static string Display_NameIdentifierField {
            get {
                return ResourceManager.GetString("Display_NameIdentifierField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name Identifier Format.
        /// </summary>
        public static string Display_NameIdentifierFormat {
            get {
                return ResourceManager.GetString("Display_NameIdentifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Email.
        /// </summary>
        public static string Display_NewEmail {
            get {
                return ResourceManager.GetString("Display_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Password.
        /// </summary>
        public static string Display_NewPassword {
            get {
                return ResourceManager.GetString("Display_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not added.
        /// </summary>
        public static string Display_NotAdded {
            get {
                return ResourceManager.GetString("Display_NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Display_Note {
            get {
                return ResourceManager.GetString("Display_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online.
        /// </summary>
        public static string Display_Online {
            get {
                return ResourceManager.GetString("Display_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Created At From.
        /// </summary>
        public static string Display_OrderCreatedAtDateFrom {
            get {
                return ResourceManager.GetString("Display_OrderCreatedAtDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Created At To.
        /// </summary>
        public static string Display_OrderCreatedAtDateTo {
            get {
                return ResourceManager.GetString("Display_OrderCreatedAtDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Status.
        /// </summary>
        public static string Display_OrderStatus {
            get {
                return ResourceManager.GetString("Display_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OS.
        /// </summary>
        public static string Display_OS {
            get {
                return ResourceManager.GetString("Display_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OTP Secret.
        /// </summary>
        public static string Display_OtpSecret {
            get {
                return ResourceManager.GetString("Display_OtpSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OTP Updated.
        /// </summary>
        public static string Display_OtpUpdated {
            get {
                return ResourceManager.GetString("Display_OtpUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Display_Password {
            get {
                return ResourceManager.GetString("Display_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password Updated.
        /// </summary>
        public static string Display_PasswordUpdated {
            get {
                return ResourceManager.GetString("Display_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        public static string Display_PhoneNumber {
            get {
                return ResourceManager.GetString("Display_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        public static string Display_Position {
            get {
                return ResourceManager.GetString("Display_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Display_Profile {
            get {
                return ResourceManager.GetString("Display_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prolong License.
        /// </summary>
        public static string Display_ProlongLicense {
            get {
                return ResourceManager.GetString("Display_ProlongLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Public x509 Certificate.
        /// </summary>
        public static string Display_PublicX509Certificate {
            get {
                return ResourceManager.GetString("Display_PublicX509Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recovery Code.
        /// </summary>
        public static string Display_RecoveryCode {
            get {
                return ResourceManager.GetString("Display_RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember machine.
        /// </summary>
        public static string Display_RememberMachine {
            get {
                return ResourceManager.GetString("Display_RememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me.
        /// </summary>
        public static string Display_RememberMe {
            get {
                return ResourceManager.GetString("Display_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID.
        /// </summary>
        public static string Display_RFID {
            get {
                return ResourceManager.GetString("Display_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Severity.
        /// </summary>
        public static string Display_Severity {
            get {
                return ResourceManager.GetString("Display_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Logout Service.
        /// </summary>
        public static string Display_SingleLogoutService {
            get {
                return ResourceManager.GetString("Display_SingleLogoutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Date.
        /// </summary>
        public static string Display_StartDate {
            get {
                return ResourceManager.GetString("Display_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Display_Status {
            get {
                return ResourceManager.GetString("Display_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Description.
        /// </summary>
        public static string Display_StatusDescription {
            get {
                return ResourceManager.GetString("Display_StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Reason.
        /// </summary>
        public static string Display_StatusReason {
            get {
                return ResourceManager.GetString("Display_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocked By.
        /// </summary>
        public static string Display_UnlockedBy {
            get {
                return ResourceManager.GetString("Display_UnlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated.
        /// </summary>
        public static string Display_Updated {
            get {
                return ResourceManager.GetString("Display_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated At From.
        /// </summary>
        public static string Display_UpdatedAtFrom {
            get {
                return ResourceManager.GetString("Display_UpdatedAtFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated At To.
        /// </summary>
        public static string Display_UpdatedAtTo {
            get {
                return ResourceManager.GetString("Display_UpdatedAtTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URLs.
        /// </summary>
        public static string Display_Urls {
            get {
                return ResourceManager.GetString("Display_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URLs (separate by semicolon).
        /// </summary>
        public static string Display_UrlsSeparate {
            get {
                return ResourceManager.GetString("Display_UrlsSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Session.
        /// </summary>
        public static string Display_UserSession {
            get {
                return ResourceManager.GetString("Display_UserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vaults Count.
        /// </summary>
        public static string Display_VaultsCount {
            get {
                return ResourceManager.GetString("Display_VaultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verification Code.
        /// </summary>
        public static string Display_VerificationCode {
            get {
                return ResourceManager.GetString("Display_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation.
        /// </summary>
        public static string Display_Workstation {
            get {
                return ResourceManager.GetString("Display_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your server has been restarted. Please activate the data protection on the server by clicking this button:.
        /// </summary>
        public static string Email_ActivateDataProtection_Body {
            get {
                return ResourceManager.GetString("Email_ActivateDataProtection_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action required - Activate the data protection.
        /// </summary>
        public static string Email_ActivateDataProtection_Subject {
            get {
                return ResourceManager.GetString("Email_ActivateDataProtection_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator.
        /// </summary>
        public static string Email_Common_Admin {
            get {
                return ResourceManager.GetString("Email_Common_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate.
        /// </summary>
        public static string Email_Common_Btn_Activate {
            get {
                return ResourceManager.GetString("Email_Common_Btn_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Email_Common_Btn_Confirm {
            get {
                return ResourceManager.GetString("Email_Common_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset Password.
        /// </summary>
        public static string Email_Common_Btn_ResetPassword {
            get {
                return ResourceManager.GetString("Email_Common_Btn_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days remaining.
        /// </summary>
        public static string Email_Common_DaysRemainin {
            get {
                return ResourceManager.GetString("Email_Common_DaysRemainin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dear {0},.
        /// </summary>
        public static string Email_Common_Dear {
            get {
                return ResourceManager.GetString("Email_Common_Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на link.
        /// </summary>
        public static string Email_Common_Link {
            get {
                return ResourceManager.GetString("Email_Common_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your {0}.
        /// </summary>
        public static string Email_Common_YourServer {
            get {
                return ResourceManager.GetString("Email_Common_YourServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve turned off the option SSO for your account..
        /// </summary>
        public static string Email_EmployeeDisableSso_Body {
            get {
                return ResourceManager.GetString("Email_EmployeeDisableSso_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO Disabled for your account.
        /// </summary>
        public static string Email_EmployeeDisableSso_Subject {
            get {
                return ResourceManager.GetString("Email_EmployeeDisableSso_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve turned on the option SSO to your account. Please complete the setup by adding a security key using this.
        /// </summary>
        public static string Email_EmployeeEnableSso_Body {
            get {
                return ResourceManager.GetString("Email_EmployeeEnableSso_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO Enabled for your account.
        /// </summary>
        public static string Email_EmployeeEnableSso_Subject {
            get {
                return ResourceManager.GetString("Email_EmployeeEnableSso_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your hardware vault activation code:.
        /// </summary>
        public static string Email_HardwareVaultActivationCode_Body {
            get {
                return ResourceManager.GetString("Email_HardwareVaultActivationCode_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate Hardware Vault.
        /// </summary>
        public static string Email_HardwareVaultActivationCode_Subject {
            get {
                return ResourceManager.GetString("Email_HardwareVaultActivationCode_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some of your Security Keys devices have changes in their license status. Please review the list below and take action if required..
        /// </summary>
        public static string Email_HardwareVaultLicenseStatus_Body {
            get {
                return ResourceManager.GetString("Email_HardwareVaultLicenseStatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Status Update.
        /// </summary>
        public static string Email_HardwareVaultLicenseStatus_Subject {
            get {
                return ResourceManager.GetString("Email_HardwareVaultLicenseStatus_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for placing the order on licenses..
        /// </summary>
        public static string Email_LicenseChanged_Body {
            get {
                return ResourceManager.GetString("Email_LicenseChanged_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The status of your license order of {0} has been changed to {1}.
        /// </summary>
        public static string Email_LicenseChanged_Description {
            get {
                return ResourceManager.GetString("Email_LicenseChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Order Status Update.
        /// </summary>
        public static string Email_LicenseChanged_Subject {
            get {
                return ResourceManager.GetString("Email_LicenseChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your password for your domain account {0} has been automatically changed and uploaded to your Security Key {1}..
        /// </summary>
        public static string Email_NotifyWhenPasswordAutoChanged_Body {
            get {
                return ResourceManager.GetString("Email_NotifyWhenPasswordAutoChanged_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please use it at the next login. Please note that your computer will need a connection to the server to sync data..
        /// </summary>
        public static string Email_NotifyWhenPasswordAutoChanged_Description {
            get {
                return ResourceManager.GetString("Email_NotifyWhenPasswordAutoChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password Auto Changed.
        /// </summary>
        public static string Email_NotifyWhenPasswordAutoChanged_Subject {
            get {
                return ResourceManager.GetString("Email_NotifyWhenPasswordAutoChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please confirm your account by clicking on the button:.
        /// </summary>
        public static string Email_UserConfirmEmail_Body {
            get {
                return ResourceManager.GetString("Email_UserConfirmEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action required - Confirm your email.
        /// </summary>
        public static string Email_UserConfirmEmail_Subject {
            get {
                return ResourceManager.GetString("Email_UserConfirmEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve been invited to server. Please confirm the invitation by entering a new password using this.
        /// </summary>
        public static string Email_UserInvitation_Body {
            get {
                return ResourceManager.GetString("Email_UserInvitation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action required - Invitation.
        /// </summary>
        public static string Email_UserInvitation_Subject {
            get {
                return ResourceManager.GetString("Email_UserInvitation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To secure your account, please reset your password by clicking on the button:.
        /// </summary>
        public static string Email_UserResetPassword_Body {
            get {
                return ResourceManager.GetString("Email_UserResetPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action required - Password reset.
        /// </summary>
        public static string Email_UserResetPassword_Subject {
            get {
                return ResourceManager.GetString("Email_UserResetPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Enum_Email {
            get {
                return ResourceManager.GetString("Enum_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External ID.
        /// </summary>
        public static string Enum_External_Id {
            get {
                return ResourceManager.GetString("Enum_External_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account with the same name and login exist..
        /// </summary>
        public static string Exception_AccountExist {
            get {
                return ResourceManager.GetString("Exception_AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account lockout.
        /// </summary>
        public static string Exception_AccountLockout {
            get {
                return ResourceManager.GetString("Exception_AccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account not found..
        /// </summary>
        public static string Exception_AccountNotFound {
            get {
                return ResourceManager.GetString("Exception_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activation Code not found.
        /// </summary>
        public static string Exception_ActivationCodeNotFound {
            get {
                return ResourceManager.GetString("Exception_ActivationCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This employee was removed from Active Directory so it was changed to a local user..
        /// </summary>
        public static string Exception_ActiveDirectoryUserNotFound {
            get {
                return ResourceManager.GetString("Exception_ActiveDirectoryUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API Key is empty..
        /// </summary>
        public static string Exception_ApiKeyEmpty {
            get {
                return ResourceManager.GetString("Exception_ApiKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application settings not found..
        /// </summary>
        public static string Exception_AppSettingsNotFound {
            get {
                return ResourceManager.GetString("Exception_AppSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The authenticator is not supporting FIDO2..
        /// </summary>
        public static string Exception_AuthenticatorNotFIDO2 {
            get {
                return ResourceManager.GetString("Exception_AuthenticatorNotFIDO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot delete default profile.
        /// </summary>
        public static string Exception_CannotDeleteDefaultProfile {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company name already in use..
        /// </summary>
        public static string Exception_CompanyNameAlreadyInUse {
            get {
                return ResourceManager.GetString("Exception_CompanyNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company not found..
        /// </summary>
        public static string Exception_CompanyNotFound {
            get {
                return ResourceManager.GetString("Exception_CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection is already activated..
        /// </summary>
        public static string Exception_DataProtectionIsAlreadyActivated {
            get {
                return ResourceManager.GetString("Exception_DataProtectionIsAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection is already enabled..
        /// </summary>
        public static string Exception_DataProtectionIsAlreadyEnabled {
            get {
                return ResourceManager.GetString("Exception_DataProtectionIsAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection is busy..
        /// </summary>
        public static string Exception_DataProtectionIsBusy {
            get {
                return ResourceManager.GetString("Exception_DataProtectionIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection is not activated..
        /// </summary>
        public static string Exception_DataProtectionNotActivated {
            get {
                return ResourceManager.GetString("Exception_DataProtectionNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection is not enabled..
        /// </summary>
        public static string Exception_DataProtectionNotEnabled {
            get {
                return ResourceManager.GetString("Exception_DataProtectionNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password change for Data Protection is not finished..
        /// </summary>
        public static string Exception_DataProtectionNotFinishedPasswordChange {
            get {
                return ResourceManager.GetString("Exception_DataProtectionNotFinishedPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Protection parameters is empty..
        /// </summary>
        public static string Exception_DataProtectionParametersIsEmpty {
            get {
                return ResourceManager.GetString("Exception_DataProtectionParametersIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data protection parameters not found..
        /// </summary>
        public static string Exception_DataProtectionParametersNotFound {
            get {
                return ResourceManager.GetString("Exception_DataProtectionParametersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department name already in use.
        /// </summary>
        public static string Exception_DepartmentNameAlreadyInUse {
            get {
                return ResourceManager.GetString("Exception_DepartmentNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department not found..
        /// </summary>
        public static string Exception_DepartmentNotFound {
            get {
                return ResourceManager.GetString("Exception_DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This email address is already taken.
        /// </summary>
        public static string Exception_EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("Exception_EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee with current name already exists..
        /// </summary>
        public static string Exception_EmployeeAlreadyExist {
            get {
                return ResourceManager.GetString("Exception_EmployeeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee not found..
        /// </summary>
        public static string Exception_EmployeeNotFound {
            get {
                return ResourceManager.GetString("Exception_EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires email..
        /// </summary>
        public static string Exception_EmployeeRequiresEmail {
            get {
                return ResourceManager.GetString("Exception_EmployeeRequiresEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSO requires last name..
        /// </summary>
        public static string Exception_EmployeeRequiresLastName {
            get {
                return ResourceManager.GetString("Exception_EmployeeRequiresLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault in a status that does not allow to reserve..
        /// </summary>
        public static string Exception_HardwareVaultCannotReserve {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultCannotReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault not found..
        /// </summary>
        public static string Exception_HardwareVaultNotFound {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault {0} not found..
        /// </summary>
        public static string Exception_HardwareVaultNotFoundWithParam {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultNotFoundWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault profile not found.
        /// </summary>
        public static string Exception_HardwareVaultProfileNotFound {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First untie the hardware vault before removing..
        /// </summary>
        public static string Exception_HardwareVaultUntieBeforeRemove {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultUntieBeforeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vault in a status that does not allow to remove..
        /// </summary>
        public static string Exception_HardwareVaultВoesNotAllowToRemove {
            get {
                return ResourceManager.GetString("Exception_HardwareVaultВoesNotAllowToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect current password..
        /// </summary>
        public static string Exception_IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("Exception_IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect old password..
        /// </summary>
        public static string Exception_IncorrectOldPassword {
            get {
                return ResourceManager.GetString("Exception_IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect OTP secret..
        /// </summary>
        public static string Exception_IncorrectOtp {
            get {
                return ResourceManager.GetString("Exception_IncorrectOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect password..
        /// </summary>
        public static string Exception_IncorrectPassword {
            get {
                return ResourceManager.GetString("Exception_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect URL address..
        /// </summary>
        public static string Exception_IncorrectUrl {
            get {
                return ResourceManager.GetString("Exception_IncorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid certificate..
        /// </summary>
        public static string Exception_InvalidCertificate {
            get {
                return ResourceManager.GetString("Exception_InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login attempt..
        /// </summary>
        public static string Exception_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Exception_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invitation not confirmed..
        /// </summary>
        public static string Exception_InvitationNotConfirmed {
            get {
                return ResourceManager.GetString("Exception_InvitationNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LDAP settings not set..
        /// </summary>
        public static string Exception_LdapSettingsNotSet {
            get {
                return ResourceManager.GetString("Exception_LdapSettingsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault licenses not found..
        /// </summary>
        public static string Exception_LicenseForHardwareVaultNotFound {
            get {
                return ResourceManager.GetString("Exception_LicenseForHardwareVaultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Order not found..
        /// </summary>
        public static string Exception_LicenseOrderNotFound {
            get {
                return ResourceManager.GetString("Exception_LicenseOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong..
        /// </summary>
        public static string Exception_None {
            get {
                return ResourceManager.GetString("Exception_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot add more than one Hardware Vault..
        /// </summary>
        public static string Exception_OneHardwareVaultConstraint {
            get {
                return ResourceManager.GetString("Exception_OneHardwareVaultConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position name already in use..
        /// </summary>
        public static string Exception_PositionNameAlreadyInUse {
            get {
                return ResourceManager.GetString("Exception_PositionNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position not found..
        /// </summary>
        public static string Exception_PositionNotFound {
            get {
                return ResourceManager.GetString("Exception_PositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name already in use.
        /// </summary>
        public static string Exception_ProfileNameAlreadyInUse {
            get {
                return ResourceManager.GetString("Exception_ProfileNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires relogin.
        /// </summary>
        public static string Exception_RequiresRelogin {
            get {
                return ResourceManager.GetString("Exception_RequiresRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires two factor..
        /// </summary>
        public static string Exception_RequiresTwoFactor {
            get {
                return ResourceManager.GetString("Exception_RequiresTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Issuer already exist..
        /// </summary>
        public static string Exception_Saml2IssuerAlreadyExist {
            get {
                return ResourceManager.GetString("Exception_Saml2IssuerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not metadata or descriptor element not found..
        /// </summary>
        public static string Exception_Saml2NotMetadataOrDescriptorElementNotFound {
            get {
                return ResourceManager.GetString("Exception_Saml2NotMetadataOrDescriptorElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service provider not found..
        /// </summary>
        public static string Exception_Saml2RelyingPartyNotFound {
            get {
                return ResourceManager.GetString("Exception_Saml2RelyingPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service Provider descriptor not loaded from metadata..
        /// </summary>
        public static string Exception_Saml2SPDescriptorNotLoaded {
            get {
                return ResourceManager.GetString("Exception_Saml2SPDescriptorNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security key not found..
        /// </summary>
        public static string Exception_SecurityKeyNotFound {
            get {
                return ResourceManager.GetString("Exception_SecurityKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Account with the same name and login exists..
        /// </summary>
        public static string Exception_SharedAccountExist {
            get {
                return ResourceManager.GetString("Exception_SharedAccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Account not found..
        /// </summary>
        public static string Exception_SharedAccountNotFound {
            get {
                return ResourceManager.GetString("Exception_SharedAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template with current name already exists..
        /// </summary>
        public static string Exception_TemplateExist {
            get {
                return ResourceManager.GetString("Exception_TemplateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Template not found..
        /// </summary>
        public static string Exception_TemplateNotFound {
            get {
                return ResourceManager.GetString("Exception_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The LDAP server is unavailable..
        /// </summary>
        public static string Exception_TheLDAPServerIsUnavailable {
            get {
                return ResourceManager.GetString("Exception_TheLDAPServerIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User not found..
        /// </summary>
        public static string Exception_UserNotFound {
            get {
                return ResourceManager.GetString("Exception_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Vault already added to workstation..
        /// </summary>
        public static string Exception_WorkstationHardwareVaultPairAlreadyExist {
            get {
                return ResourceManager.GetString("Exception_WorkstationHardwareVaultPairAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation and Hardware Vault pair not found..
        /// </summary>
        public static string Exception_WorkstationHardwareVaultPairNotFound {
            get {
                return ResourceManager.GetString("Exception_WorkstationHardwareVaultPairNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation not found..
        /// </summary>
        public static string Exception_WorkstationNotFound {
            get {
                return ResourceManager.GetString("Exception_WorkstationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workstation {0} not found..
        /// </summary>
        public static string Exception_WorkstationNotFoundWithParam {
            get {
                return ResourceManager.GetString("Exception_WorkstationNotFoundWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The new password and password confirmation do not match..
        /// </summary>
        public static string Validation_CompareNewPassword {
            get {
                return ResourceManager.GetString("Validation_CompareNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password and password confirmation do not match..
        /// </summary>
        public static string Validation_ComparePassword {
            get {
                return ResourceManager.GetString("Validation_ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} field is not a valid e-mail address..
        /// </summary>
        public static string Validation_EmailAddress {
            get {
                return ResourceManager.GetString("Validation_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field {0} must be between {1} and {2}..
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} field is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The {0} field is not a valid fully-qualified http, https, or ftp URL..
        /// </summary>
        public static string Validation_Url {
            get {
                return ResourceManager.GetString("Validation_Url", resourceCulture);
            }
        }
    }
}
